export {Banner} from './banner/Banner'
export {MiniCatalog} from './miniCatalog/MiniCatalog'
export {CompanyInfo} from './companyInfo/CompanyInfo'
export {Catalog} from './catalog/Catalog'
export {Brands} from './brands/Brands'